// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWinnicode.Data;

#nullable disable

namespace TestWinnicode.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250529145307_AddKategoriAndSubKategori")]
    partial class AddKategoriAndSubKategori
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TestWinnicode.Models.Berita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Jumlah_View")
                        .HasColumnType("int");

                    b.Property<string>("Penulis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SubKategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tanggal_Publish")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SubKategoriId");

                    b.ToTable("Berita");
                });

            modelBuilder.Entity("TestWinnicode.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("TestWinnicode.Models.SubKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("SubKategori");
                });

            modelBuilder.Entity("TestWinnicode.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestWinnicode.Models.Berita", b =>
                {
                    b.HasOne("TestWinnicode.Models.SubKategori", "SubKategori")
                        .WithMany("Beritas")
                        .HasForeignKey("SubKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubKategori");
                });

            modelBuilder.Entity("TestWinnicode.Models.SubKategori", b =>
                {
                    b.HasOne("TestWinnicode.Models.Kategori", "Kategori")
                        .WithMany("SubKategoris")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("TestWinnicode.Models.Kategori", b =>
                {
                    b.Navigation("SubKategoris");
                });

            modelBuilder.Entity("TestWinnicode.Models.SubKategori", b =>
                {
                    b.Navigation("Beritas");
                });
#pragma warning restore 612, 618
        }
    }
}
